name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-2019]

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: 5.3.x

    - name: Remove .DS_Store files
      run: |
        Get-ChildItem -Path . -Recurse -Include .DS_Store | Remove-Item -Force
      shell: pwsh

    - name: Restore NuGet packages
      run: nuget restore src/Check_Inn.sln

    - name: Build the Solution
      run: |
        msbuild src/Check_Inn.sln `
          /p:Configuration=Release `
          /p:DeployOnBuild=true `
          /p:PublishProfile=FolderProfile 

    - name: 'Deploy to Azure Web App Service'
      uses: azure/webapps-deploy@v3
      with:
        app-name: check-inn
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'src\bin\check_inn.publish'
